name: Spellcheck
on:
  pull_request:
    paths:
    - 'README.md'
  workflow_dispatch:
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@v0.5.0
